[package]
name = "ovr_overlay"
version = "0.0.0"
description = "Rust bindings for OpenVR overlays"
edition = "2021"
authors = ["Ryan Butler <thebutlah@gmail.com>"]
license = "MIT OR Apache-2.0"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ovr_overlay_sys = { path = "sys" }
lazy_static = "1"
thiserror = "1"
derive_more = "0.99"
log = "0.4"
nalgebra = { version = "0.30", optional = true }
slice-of-array = "0.3"


[workspace]
members = ["sys"]
