[package]
name = "ovr_overlay_sys"
version = "0.0.1"
edition = "2021"
links = "openvr_api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "0.21"
cxx = "1"

[build-dependencies]
autocxx-build = "0.21"
normpath = "0.3"
